x11()
data<-read.csv("F:ch11data.csv",head=T)
train<-data[which(data$平均线!="无"),]
test<-data[which(data$平均线=="无"),]
train$平均线<-as.numeric(as.character(train$平均线))
summary(train$平均线)
a<-as.data.frame(table(train$平均线))
plot(a,xlab="录取平均分",ylab="院校的数量")
b<-as.data.frame(table(train$类型))
barplot(b$Freq,names.arg=b$Var1,col=rainbow(12),xlab="院校类型",ylab="院校的数量",main="院校分布")
c<-as.data.frame(table(train$是否985))
barplot(c$Freq,names.arg=c$Var1,xlab="是否为985院校",ylab="院校的数量")
d1<-as.data.frame(table(train$重点学科))
plot(d1,xlab="重点学科",ylab="数量")
d2<-as.data.frame(table(train$博士点))
plot(d2,xlab="博士点",ylab="数量")

n<-train[which(train$是否985=="否" & train$是否211=="否"),]
set.seed(1)
m<-dim(train)[1]
pre<-sample(m,m*0.75)
pre<-sort(pre)
train1<-n[pre,]
test1<-n[-pre,]
train1$所在地<-as.numeric(as.factor(train1$所在地))
train1$隶属<-as.numeric(as.factor(train1$隶属))
train1$重点学科<-as.numeric(train1$重点学科)
train1$平均线<-as.numeric(as.character(train1$平均线))
#train1$是否自主招生<-as.numeric(as.factor(train1$是否自主招生))
fit<-lm(平均线~院士+硕士点+类型+重点学科+博士点,data=train1)
summary(fit)
#plot(fit)
#模型预测
pred<-predict(fit,test1[,c("院士","硕士点","类型","重点学科","博士点")])
#计算MSE
RMSE<-function(t,p)
{
  return(sqrt(mean((t-p)^2)))
}
RMSE(test1$平均线,pred)
# 绘制测试集真实值和预测值曲线
# 将画布分为2行2列
par(mfrow=c(2,2))
plot(1:length(test1$平均线),test1$平均线,type="l",col="blue")
plot(1:length(test1$平均线),pred,type="l",col="red")
# 绘制测试集真实值和预测值曲线
plot(1:length(test1$平均线),test1$平均线,type="l",col="blue",main="真实值和预测值对比曲线")
lines(1:length(test1$平均线),pred,col="red")
n1<-test[which(test$是否985=="否"&test$是否211=="否"),]
pred1<-predict(fit,n1[,c("院士","硕士点","类型","重点学科","博士点")])
pred1
n2<-train[which(train$是否211=="是"),]
m1<-dim(train)[1]
pre1<-sample(m1,m1*0.75)
pre1<-sort(pre1)
train2<-n2[pre1,]
test2<-n2[-pre1,]
train2$所在地<-as.numeric(as.factor(train2$所在地))
train2$隶属<-as.numeric(as.factor(train2$隶属))
train2$重点学科<-as.numeric(train2$重点学科)
train2$平均线<-as.numeric(as.character(train2$平均线))
fit1<-lm(平均线~院士+硕士点+重点学科+博士点,data=train2)
summary(fit1)
pred2<-predict(fit1,test2[,c("院士","硕士点","重点学科","博士点")])
RMSE<-function(t,p)
{
  return(sqrt(mean((t-p)^2)))
}
RMSE(test2$平均线,pred2)
par(mfrow=c(2,2))
plot(1:length(test2$平均线),test2$平均线,type="l",col="blue")
plot(1:length(test2$平均线),pred2,type="l",col="red")
plot(1:length(test2$平均线),test2$平均线,type="l",col="blue",main="真实值和预测值对比曲线")
lines(1:length(test2$平均线),pred2,col="red")
n3<-test[which(test$是否211=="是"),]
pred3<-predict(fit1,n3[,c("院士","硕士点","重点学科","博士点")])
pred3

